# Generated by Django 6.0.3 on 2026-03-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='sights/', verbose_name='Изображение')),
                ('opening_hours', models.CharField(blank=True, max_length=200, null=True, verbose_name='Часы работы')),
                ('ticket_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стоимость билета')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sights', to='sights.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'ordering': ['name'],
            },
        ),
    ]
