# Generated by Django 6.0.3 on 2026-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_sight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Изображение'),
        ),
    ]
