# Generated by Django 6.0.3 on 2026-03-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0003_alter_sight_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
