# Generated by Django 6.0.3 on 2026-04-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0005_sight_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='opening_hours',
            field=models.CharField(blank=True, default='Не указано', max_length=200, null=True, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='ticket_price',
            field=models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Стоимость билета'),
        ),
    ]
