# Generated by Django 6.0.3 on 2026-04-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0006_alter_sight_opening_hours_alter_sight_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='owner',
        ),
    ]
