# Generated by Django 6.0.3 on 2026-04-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0007_remove_sight_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sights/gallery/%Y/%m/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sights.sight', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотогалерея',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
