# Generated by Django 6.0.3 on 2026-04-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0008_sightphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sightphoto',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотогалерея'},
        ),
        migrations.RemoveField(
            model_name='sightphoto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sightphoto',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sightphoto',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sightphoto',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='sightphoto',
            name='image',
            field=models.ImageField(upload_to='sights/gallery/', verbose_name='Фотография'),
        ),
    ]
