# Generated by Django 6.0.3 on 2026-04-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0009_alter_sightphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='views_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
    ]
