# Generated by Django 6.0.3 on 2026-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0010_alter_sight_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Например: 68.9707', null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='sight',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Например: 33.0749', null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='sight',
            name='map_zoom',
            field=models.IntegerField(default=15, help_text='От 1 до 19', verbose_name='Масштаб карты'),
        ),
    ]
