# Generated by Django 6.0.3 on 2026-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0011_sight_latitude_sight_longitude_sight_map_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='map_zoom',
        ),
    ]
