# Generated by Django 6.0.3 on 2026-04-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0013_sight_latitude_sight_longitude_sight_map_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='map_zoom',
        ),
        migrations.AddField(
            model_name='sight',
            name='website',
            field=models.URLField(blank=True, help_text='Например: https://example.com', null=True, verbose_name='Официальный сайт'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
